### PR TITLE
Compatibility up to 9.3.3

### PR DESCRIPTION
**Pull request by Megachip**
For discussion see issue #11

### CODE REVIEW

**Comment by judihui69** [comment]
Install is now also possible on 9.4.2
But after assigning a user to a license (user_softwarelicense.form.php)i get a http 500 error. Any idea?

**Comment by Megachip** [comment]
@judihui69 yeah, not compatible with 9.4 branch :(

**Comment by prybak** [comment]
@Megachip, @judihui69  please change line 12 in front/softwarelicense.form.php to:
         Glpi\Event::log($_POST['softwarelicenses_id'], "softwarelicense", 4, "inventory",

Or add before include use Glpi\Event.

Please let me know if it solved your issue.

**Comment by judihui69** [comment]
Hi prybak
Thanks a lot for your change! Now the 500 error is gone… but if i assign a license to a user object, the list keeps empty. "no item found". Also no license entry in the users object. Am i doing something wrong?

**Comment by prybak** [comment]
I will take a look at it.

**Comment by prybak** [comment]
Hmmm I've just tested it at our prod and test environment. It seems to be working properly.
Do you have any error message in log files?

**Comment by judihui69** [comment]
thank you very much
________________________________

**Comment by judihui69** [comment]
Maybe it has someting to do with fusioninventory... what do you mean?

[2019-05-06 11:27:50] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 659
  *** PHP Notice(8): Trying to get property 'num_rows' of non-object
  Backtrace :
  inc\dbmysql.class.php:285
  plugins\fpsoftware\inc\common.class.php:154        DBmysql->numrows()
  plugins\fpsoftware\inc\common.class.php:352        PluginFpsoftwareCommon::countForLicense()
  inc\commonglpi.class.php:210                       PluginFpsoftwareCommon->getTabNameForItem()
  inc\commonglpi.class.php:173                       CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:707                       CommonGLPI->defineAllTabs()
  inc\commonglpi.class.php:1005                      CommonGLPI->showTabsContent()
  front\softwarelicense.form.php:99                  CommonGLPI->display()
  {"user":"287@SERVER00","mem_usage":"0.002\", 2.73Mio)"}
________________________________
Von: prybak <notifications@github.com>
Gesendet: Montag, 6. Mai 2019 10:40
An: FutureProcessing/glpi-fpsoftware
Cc: judihui69; Mention
Betreff: Re: [FutureProcessing/glpi-fpsoftware] Compatibility up to 9.3.3 (#12)


Hmmm I've just tested it at our prod and test environment. It seems to be working properly.
Do you have any error message in log files?

**Comment by judihui69** [comment]
Or this entry from the sql log

[2019-05-06 11:27:58] glpisqllog.ERROR: DBmysql::query() in C:\xampp\htdocs\glpi\inc\dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
                       FROM `glpi_users_softwarelicenses`
                       INNER JOIN `glpi_users`
                           ON (`glpi_users_softwarelicenses`.`users_id`
                                 = `glpi_users`.`id`)
                       WHERE `glpi_users_softwarelicenses`.`softwarelicenses_id` = '3'
  Error: Table 'glpi.glpi_users_softwarelicenses' doesn't exist
  Backtrace :
  plugins\fpsoftware\inc\common.class.php:201
  plugins\fpsoftware\inc\common.class.php:373        PluginFpsoftwareCommon::showForLicense()
  inc\commonglpi.class.php:485                       PluginFpsoftwareCommon::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"287@SERVER00"}

________________________________
Von: prybak <notifications@github.com>
Gesendet: Montag, 6. Mai 2019 10:40
An: FutureProcessing/glpi-fpsoftware
Cc: judihui69; Mention
Betreff: Re: [FutureProcessing/glpi-fpsoftware] Compatibility up to 9.3.3 (#12)


Hmmm I've just tested it at our prod and test environment. It seems to be working properly.
Do you have any error message in log files?

**Comment by prybak** [comment]
Seems like you are missing a table :). Did you install the plugin correctly? Did you encounter any issue during the install?

Please create missing table by using following script:
CREATE TABLE IF NOT EXISTS `glpi_users_softwarelicenses` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `users_id` int(11) NOT NULL,
            `softwarelicenses_id` int(11) NOT NULL,
            `added` datetime NOT NULL,
            PRIMARY KEY (`id`)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by judihui69** [comment]
hey prybak

you are fabulous!

excellent... the plugin is now working as it should..

problem solved...

best regards
Marcel

________________________________
Von: prybak <notifications@github.com>
Gesendet: Montag, 6. Mai 2019 12:13
An: FutureProcessing/glpi-fpsoftware
Cc: judihui69; Mention
Betreff: Re: [FutureProcessing/glpi-fpsoftware] Compatibility up to 9.3.3 (#12)


Seems like you are missing a table :). Did you install the plugin correctly? Did you encounter any issue during the install?

Please create missing table by using following script:
CREATE TABLE IF NOT EXISTS glpi_users_softwarelicenses (
id int(11) NOT NULL AUTO_INCREMENT,
users_id int(11) NOT NULL,
softwarelicenses_id int(11) NOT NULL,
added datetime NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by prybak** [comment]
Awesome, solved :).

**Pull request merged**
